export type PageMode = "understand" | "observe" | "operate" | "showcase";
export type PageDomain =
  | "command"
  | "finance"
  | "manufacturing"
  | "inventory"
  | "procurement"
  | "engineering"
  | "epr"
  | "knowledge"
  | "sales"
  | "market"
  | "legal"
  | "risk"
  | "leadership"
  | "admin";
export type PageOwner =
  | "founder"
  | "board"
  | "finance"
  | "operations"
  | "engineering"
  | "qa"
  | "compliance"
  | "sales"
  | "market"
  | "legal"
  | "risk"
  | "investors"
  | "knowledge"
  | "all";
export type PageMaturity = "keep" | "merge" | "review";
export type NavigationGroup =
  "Command" | "Planning" | "Understand" | "Observe" | "Operate" | "Showcase";
export type RouteSource = "operational" | "planning" | "reference" | "showcase";
export type RouteMutability = "read-only" | "editable";
export interface PageMeta {
  mode: PageMode;
  domain: PageDomain;
  owner: PageOwner;
  maturity: PageMaturity;
  group: NavigationGroup;
  navHidden?: boolean;
  adminOnly?: boolean;
}
export interface RouteMeta extends PageMeta {
  route: string;
  label: string;
}
export interface RouteOwnership {
  canonicalRoute: string;
  source: RouteSource;
  mutability: RouteMutability;
  compatibility?: boolean;
  notes: string;
}
type PageOptions = Pick<PageMeta, "navHidden" | "adminOnly">;
const meta = (
  route: string,
  label: string,
  mode: PageMode,
  domain: PageDomain,
  owner: PageOwner,
  maturity: PageMaturity,
  group: NavigationGroup,
  options: PageOptions = {},
): RouteMeta => ({ route, label, mode, domain, owner, maturity, group, ...options });
export const routeRegistry: Record<string, RouteMeta> = {
  "/inventory": meta(
    "/inventory",
    "Component Catalogue (legacy)",
    "understand",
    "inventory",
    "operations",
    "review",
    "Understand",
    { navHidden: true },
  ),
  "/command": meta("/command", "Board", "observe", "command", "board", "keep", "Command"),
  "/command/control-tower": meta(
    "/command/control-tower",
    "Command Tower",
    "observe",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/ibpe-operating-workspace": meta(
    "/command/ibpe-operating-workspace",
    "IBPE Operating Workspace",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
    { navHidden: true },
  ),
  "/command/management-intelligence": meta(
    "/command/management-intelligence",
    "Management Intelligence",
    "observe",
    "command",
    "founder",
    "keep",
    "Command",
    { navHidden: true },
  ),
  "/command/governance": meta(
    "/command/governance",
    "Governance & Approvals",
    "observe",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/founder-command": meta(
    "/command/founder-command",
    "Founder Command",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/founder-control": meta(
    "/command/founder-control",
    "Founder Control",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/decision-engine": meta(
    "/command/decision-engine",
    "Decision Engine",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/decision-inbox": meta(
    "/command/decision-inbox",
    "Business Action Inbox",
    "observe",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/classification": meta(
    "/command/classification",
    "Classification",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/master-data": meta(
    "/command/master-data",
    "Master Data Engine",
    "operate",
    "admin",
    "founder",
    "keep",
    "Command",
  ),
  "/command/users": meta(
    "/command/users",
    "User Access Control",
    "operate",
    "admin",
    "founder",
    "keep",
    "Command",
  ),
  "/command/recovery": meta(
    "/command/recovery",
    "Backup & Recovery Centre",
    "operate",
    "admin",
    "founder",
    "keep",
    "Command",
    { adminOnly: true },
  ),
  "/command/investor-board": meta(
    "/command/investor-board",
    "Investor / Board",
    "observe",
    "command",
    "investors",
    "keep",
    "Observe",
  ),
  "/command/knowledge": meta(
    "/command/knowledge",
    "Knowledge Base",
    "understand",
    "knowledge",
    "all",
    "keep",
    "Understand",
  ),
  "/command/technical": meta(
    "/command/technical",
    "Technical",
    "understand",
    "knowledge",
    "engineering",
    "keep",
    "Understand",
  ),
  "/command/design-philosophy": meta(
    "/command/design-philosophy",
    "Design Philosophy",
    "understand",
    "knowledge",
    "founder",
    "keep",
    "Understand",
  ),
  "/command/ai-knowledge": meta(
    "/command/ai-knowledge",
    "AI Knowledge",
    "understand",
    "knowledge",
    "all",
    "merge",
    "Understand",
  ),
  "/command/balance-sheet": meta(
    "/command/balance-sheet",
    "Balance Sheet",
    "observe",
    "finance",
    "finance",
    "keep",
    "Observe",
  ),
  "/command/finance": meta(
    "/command/finance",
    "Finance Dashboard",
    "observe",
    "finance",
    "finance",
    "keep",
    "Observe",
  ),
  "/command/ca-audit": meta(
    "/command/ca-audit",
    "CA Verification / Audit",
    "observe",
    "finance",
    "finance",
    "keep",
    "Observe",
  ),
  "/command/scenarios": meta(
    "/command/scenarios",
    "Scenario Analysis",
    "observe",
    "finance",
    "founder",
    "keep",
    "Planning",
  ),
  "/command/qa-verification": meta(
    "/command/qa-verification",
    "QA Verification",
    "observe",
    "manufacturing",
    "qa",
    "review",
    "Observe",
  ),
  "/command/epr-live": meta(
    "/command/epr-live",
    "Live EPR Transactions",
    "operate",
    "epr",
    "compliance",
    "keep",
    "Operate",
  ),
  "/command/planning": meta(
    "/command/planning",
    "Integrated Operating Plan",
    "operate",
    "command",
    "founder",
    "keep",
    "Planning",
  ),
  "/command/finance-assumptions": meta(
    "/command/finance-assumptions",
    "Forecast Parameters",
    "operate",
    "finance",
    "finance",
    "keep",
    "Planning",
  ),
  "/command/master-finance": meta(
    "/command/master-finance",
    "Consolidated Finance (compatibility)",
    "operate",
    "finance",
    "finance",
    "merge",
    "Planning",
  ),
  "/command/finance-control": meta(
    "/command/finance-control",
    "Budget vs Forecast vs Actual",
    "operate",
    "finance",
    "finance",
    "keep",
    "Operate",
  ),
  "/command/funding": meta(
    "/command/funding",
    "Funding Intelligence",
    "operate",
    "finance",
    "founder",
    "keep",
    "Planning",
  ),
  "/command/cash": meta(
    "/command/cash",
    "Cash & Working Capital",
    "operate",
    "finance",
    "finance",
    "keep",
    "Operate",
  ),
  "/command/payables": meta(
    "/command/payables",
    "Accounts Payable",
    "operate",
    "finance",
    "finance",
    "keep",
    "Operate",
  ),
  "/command/receivables": meta(
    "/command/receivables",
    "Accounts Receivable",
    "observe",
    "finance",
    "finance",
    "keep",
    "Observe",
  ),
  "/command/operations": meta(
    "/command/operations",
    "Operations Model (planning)",
    "operate",
    "procurement",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/procurement": meta(
    "/command/procurement",
    "Procurement Control",
    "operate",
    "procurement",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/procurement-planning": meta(
    "/command/procurement-planning",
    "Procurement Planning (editable)",
    "operate",
    "procurement",
    "operations",
    "keep",
    "Planning",
  ),
  "/command/purchase-execution": meta(
    "/command/purchase-execution",
    "Purchase Execution",
    "operate",
    "procurement",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/receiving": meta(
    "/command/receiving",
    "Receiving & Inspection",
    "operate",
    "procurement",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/actuals": meta(
    "/command/actuals",
    "Operational Actuals",
    "observe",
    "procurement",
    "operations",
    "keep",
    "Observe",
  ),
  "/command/inventory": meta(
    "/command/inventory",
    "Master Inventory",
    "operate",
    "inventory",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/inventory-stocktake": meta(
    "/command/inventory-stocktake",
    "Inventory Stocktake",
    "operate",
    "inventory",
    "operations",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/inventory-master": meta(
    "/command/inventory-master",
    "Inventory Master",
    "operate",
    "inventory",
    "operations",
    "keep",
    "Operate",
    { navHidden: true, adminOnly: true },
  ),
  "/command/inventory-truth": meta(
    "/command/inventory-truth",
    "Inventory Truth",
    "observe",
    "inventory",
    "operations",
    "keep",
    "Observe",
    { navHidden: true, adminOnly: true },
  ),
  "/command/inventory-openings": meta(
    "/command/inventory-openings",
    "Inventory Opening Balances",
    "operate",
    "inventory",
    "operations",
    "keep",
    "Operate",
    { navHidden: true, adminOnly: true },
  ),
  "/command/inventory-ledgers": meta(
    "/command/inventory-ledgers",
    "Inventory Ledger Index",
    "operate",
    "inventory",
    "operations",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/inventory-control-audit": meta(
    "/command/inventory-control-audit",
    "Inventory Control Audit",
    "observe",
    "inventory",
    "operations",
    "keep",
    "Observe",
    { navHidden: true, adminOnly: true },
  ),
  "/command/component-control": meta(
    "/command/component-control",
    "Component Control (compatibility)",
    "operate",
    "inventory",
    "operations",
    "review",
    "Operate",
    { navHidden: true, adminOnly: true },
  ),
  "/command/inventory-legacy": meta(
    "/command/inventory-legacy",
    "Legacy Inventory Controls",
    "operate",
    "admin",
    "founder",
    "review",
    "Operate",
    { navHidden: true, adminOnly: true },
  ),
  "/command/production": meta(
    "/command/production",
    "Production Planning",
    "operate",
    "manufacturing",
    "operations",
    "keep",
    "Planning",
  ),
  "/command/production-jobcards": meta(
    "/command/production-jobcards",
    "Production Job Cards (compatibility)",
    "operate",
    "manufacturing",
    "operations",
    "review",
    "Operate",
    { navHidden: true },
  ),
  "/command/manufacturing": meta(
    "/command/manufacturing",
    "Manufacturing Controls",
    "operate",
    "manufacturing",
    "operations",
    "keep",
    "Operate",
  ),
  "/command/quality": meta(
    "/command/quality",
    "Quality Control",
    "operate",
    "manufacturing",
    "qa",
    "keep",
    "Operate",
  ),
  "/command/product": meta(
    "/command/product",
    "Product",
    "operate",
    "engineering",
    "engineering",
    "keep",
    "Operate",
  ),
  "/command/bom": meta(
    "/command/bom",
    "BOM & Cost Engine (planning)",
    "operate",
    "engineering",
    "engineering",
    "keep",
    "Operate",
  ),
  "/command/bom-control": meta(
    "/command/bom-control",
    "BOM Control",
    "operate",
    "engineering",
    "engineering",
    "keep",
    "Operate",
  ),
  "/command/bom-inventory-mapping": meta(
    "/command/bom-inventory-mapping",
    "BOM → Inventory Mapping",
    "operate",
    "inventory",
    "operations",
    "merge",
    "Operate",
    { navHidden: true, adminOnly: true },
  ),
  "/command/engineering": meta(
    "/command/engineering",
    "Engineering Control",
    "operate",
    "engineering",
    "engineering",
    "keep",
    "Operate",
  ),
  "/command/epr-workflow": meta(
    "/command/epr-workflow",
    "EPR Workflow",
    "operate",
    "epr",
    "compliance",
    "keep",
    "Operate",
  ),
  "/command/epr-execution": meta(
    "/command/epr-execution",
    "EPR Execution",
    "operate",
    "epr",
    "compliance",
    "keep",
    "Operate",
  ),
  "/command/investor-pitch": meta(
    "/command/investor-pitch",
    "Investor Demo",
    "showcase",
    "command",
    "investors",
    "keep",
    "Showcase",
  ),
  "/command/investor-pitch-external": meta(
    "/command/investor-pitch-external",
    "External Business Review",
    "showcase",
    "command",
    "investors",
    "keep",
    "Showcase",
  ),
  "/command/stakeholder-portal": meta(
    "/command/stakeholder-portal",
    "Business Story",
    "showcase",
    "leadership",
    "investors",
    "keep",
    "Showcase",
  ),
  "/command/platform-walkthrough": meta(
    "/command/platform-walkthrough",
    "Platform Walkthrough",
    "showcase",
    "command",
    "investors",
    "keep",
    "Showcase",
  ),
  "/command/demo-company": meta(
    "/command/demo-company",
    "Demo Company",
    "showcase",
    "command",
    "investors",
    "keep",
    "Showcase",
  ),
  "/command/financial-cockpit": meta(
    "/command/financial-cockpit",
    "Consolidated Finance Overview",
    "observe",
    "finance",
    "founder",
    "keep",
    "Observe",
  ),
  "/command/phase-4": meta(
    "/command/phase-4",
    "Phase 4 · Sales & Revenue",
    "operate",
    "sales",
    "sales",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/phase-5": meta(
    "/command/phase-5",
    "Phase 5 · Engineering + QC",
    "operate",
    "engineering",
    "engineering",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/phase-6": meta(
    "/command/phase-6",
    "Phase 6 · Pilot Production",
    "operate",
    "manufacturing",
    "operations",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/phase-6a": meta(
    "/command/phase-6a",
    "Phase 6A · EPR Execution",
    "operate",
    "epr",
    "compliance",
    "keep",
    "Operate",
    { navHidden: true },
  ),
  "/command/deployment-readiness": meta(
    "/command/deployment-readiness",
    "Deployment Readiness",
    "observe",
    "command",
    "founder",
    "keep",
    "Command",
  ),
  "/command/aluminium-finance": meta(
    "/command/aluminium-finance",
    "Aluminium Vertical",
    "observe",
    "finance",
    "founder",
    "review",
    "Observe",
  ),
  "/command/ops": meta(
    "/command/ops",
    "Ops (compatibility)",
    "operate",
    "procurement",
    "operations",
    "review",
    "Operate",
    { navHidden: true },
  ),
  "/command/sales": meta(
    "/command/sales",
    "Sales Planning",
    "operate",
    "sales",
    "sales",
    "keep",
    "Planning",
  ),
  "/command/market-survey": meta(
    "/command/market-survey",
    "Market Survey",
    "understand",
    "market",
    "market",
    "keep",
    "Understand",
  ),
  "/command/gtm": meta("/command/gtm", "GTM", "operate", "sales", "market", "keep", "Planning"),
  "/command/legal": meta(
    "/command/legal",
    "Legal",
    "understand",
    "legal",
    "legal",
    "keep",
    "Understand",
  ),
  "/command/legal-control": meta(
    "/command/legal-control",
    "Legal Control",
    "operate",
    "legal",
    "legal",
    "keep",
    "Operate",
  ),
  "/command/risk": meta("/command/risk", "Risk", "observe", "risk", "risk", "keep", "Observe"),
  "/command/actions": meta(
    "/command/actions",
    "Action Log",
    "operate",
    "command",
    "founder",
    "keep",
    "Command",
  ),
};
export const navigationGroups: Record<NavigationGroup, RouteMeta[]> = {
  Command: [],
  Planning: [],
  Understand: [],
  Observe: [],
  Operate: [],
  Showcase: [],
};
for (const page of Object.values(routeRegistry))
  if (!page.navHidden) navigationGroups[page.group].push(page);
export const pagesByMode: Record<PageMode, RouteMeta[]> = {
  observe: Object.values(routeRegistry).filter((p) => p.mode === "observe"),
  operate: Object.values(routeRegistry).filter((p) => p.mode === "operate"),
  understand: Object.values(routeRegistry).filter((p) => p.mode === "understand"),
  showcase: Object.values(routeRegistry).filter((p) => p.mode === "showcase"),
};
export const getRouteMeta = (route: string) => routeRegistry[route];
export const getNavigationGroup = (group: NavigationGroup) => navigationGroups[group];
export const routeOwnership: Record<string, RouteOwnership> = {
  "/inventory": {
    canonicalRoute: "/command/inventory",
    source: "reference",
    mutability: "editable",
    compatibility: true,
    notes:
      "Hidden legacy component catalogue retained for compatibility; Master Inventory owns operational stock.",
  },
  "/command/inventory": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "editable",
    notes: "Canonical server-backed item, MSL, demand-plan, receipt and health workspace.",
  },
  "/command/inventory-stocktake": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "editable",
    notes:
      "Hidden controlled stocktake surface owned by canonical Master Inventory; physical-count evidence, maker/checker variance approval, FIFO adjustment and accounting linkage remain inside the single inventory workspace.",
  },
  "/command/inventory-master": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "editable",
    compatibility: true,
    notes: "Admin-only legacy SKU approval workflow retained for migration and audit.",
  },
  "/command/bom": {
    canonicalRoute: "/command/bom-control",
    source: "planning",
    mutability: "editable",
    notes: "Costing and scenario companion; controlled BOM identity belongs to BOM Control.",
  },
  "/command/inventory-ledgers": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "read-only",
    compatibility: true,
    notes: "Compatibility index redirects to the canonical Master Inventory workspace.",
  },
  "/command/inventory-ledgers/:ledger": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "editable",
    notes: "Server-backed audit spreadsheet with item-specific FIFO issue allocation.",
  },
  "/command/inventory-truth": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "read-only",
    compatibility: true,
    notes: "Admin-only legacy posted-balance read model retained for reconciliation.",
  },
  "/command/inventory-legacy": {
    canonicalRoute: "/command/inventory",
    source: "operational",
    mutability: "read-only",
    compatibility: true,
    notes: "Admin-only directory for superseded inventory screens.",
  },
  "/command/procurement-planning": {
    canonicalRoute: "/command/procurement-planning",
    source: "planning",
    mutability: "editable",
    notes: "Planning assumptions consume inventory signals; they do not own balances.",
  },
  "/command/purchase-execution": {
    canonicalRoute: "/command/purchase-execution",
    source: "operational",
    mutability: "editable",
    notes: "Canonical authorised supplier and purchase-order transaction workspace.",
  },
  "/command/receiving": {
    canonicalRoute: "/command/receiving",
    source: "operational",
    mutability: "editable",
    notes: "Canonical GRN and incoming-inspection transaction workspace; accepted stock posts to Master Inventory.",
  },
  "/command": {
    canonicalRoute: "/command",
    source: "operational",
    mutability: "read-only",
    notes: "Canonical Command Centre executive workspace; it reads governed evidence without owning domain transactions.",
  },
  "/command/planning": {
    canonicalRoute: "/command/planning",
    source: "planning",
    mutability: "editable",
    notes: "Canonical 36-month Integrated Operating Plan and governed company-planning lifecycle.",
  },
  "/command/engineering": {
    canonicalRoute: "/command/engineering",
    source: "operational",
    mutability: "editable",
    notes: "Canonical Engineering workspace for controlled product, design, BOM and validation authority.",
  },
  "/command/operations": {
    canonicalRoute: "/command/operations",
    source: "operational",
    mutability: "editable",
    notes: "Canonical Supply & Production workspace coordinating procurement, inventory, production and quality execution.",
  },
  "/command/sales": {
    canonicalRoute: "/command/sales",
    source: "operational",
    mutability: "editable",
    notes: "Canonical Commercial workspace for centrally persisted demand and Sales Order revisions.",
  },
  "/command/governance": {
    canonicalRoute: "/command/governance",
    source: "operational",
    mutability: "read-only",
    notes: "Canonical Governance workspace for approvals, risk, legal, QA evidence and controlled actions.",
  },
  "/command/actuals": {
    canonicalRoute: "/command/actuals",
    source: "operational",
    mutability: "read-only",
    notes: "Read model of operational actuals; source transactions remain in domain workflows.",
  },
  "/command/finance": {
    canonicalRoute: "/command/financial-cockpit",
    source: "planning",
    mutability: "read-only",
    compatibility: true,
    notes: "Compatibility route only; the Financial Cockpit is the canonical Finance workspace.",
  },
  "/command/finance-assumptions": {
    canonicalRoute: "/command/finance-assumptions",
    source: "planning",
    mutability: "editable",
    notes: "Editable scenario, operating and accounting assumptions; does not post ERP facts.",
  },
  "/command/financial-cockpit": {
    canonicalRoute: "/command/financial-cockpit",
    source: "planning",
    mutability: "read-only",
    notes: "Executive projection consuming planning assumptions and accounting model outputs.",
  },
  "/command/balance-sheet": {
    canonicalRoute: "/command/balance-sheet",
    source: "planning",
    mutability: "read-only",
    notes: "Management accounting projection requiring CA reconciliation before statutory use.",
  },
  "/command/cash": {
    canonicalRoute: "/command/cash",
    source: "planning",
    mutability: "editable",
    notes:
      "Scenario cash and working-capital projection; inventory facts remain in Inventory Truth.",
  },
  "/command/payables": {
    canonicalRoute: "/command/payables",
    source: "operational",
    mutability: "editable",
    notes: "Canonical supplier invoice, three-way match and payment workspace.",
  },
  "/command/receivables": {
    canonicalRoute: "/command/receivables",
    source: "operational",
    mutability: "editable",
    notes: "Canonical receivable read/action surface over shipment, invoice and collection ledgers.",
  },
  "/command/decision-inbox": {
    canonicalRoute: "/command/decision-inbox",
    source: "operational",
    mutability: "read-only",
    notes: "Derived exception and approval queue; actions remain in their canonical owning workspaces.",
  },
  "/command/control-tower": {
    canonicalRoute: "/command/control-tower",
    source: "operational",
    mutability: "read-only",
    notes: "Executive read model linking gate status to operational evidence.",
  },
  "/command/management-intelligence": {
    canonicalRoute: "/command/management-intelligence",
    source: "planning",
    mutability: "read-only",
    notes: "Management projection; figures remain assumptions until evidence is reconciled.",
  },
  "/command/investor-board": {
    canonicalRoute: "/command/investor-board",
    source: "showcase",
    mutability: "read-only",
    notes: "Board and investor decision read model over controlled registers.",
  },
  "/command/investor-pitch": {
    canonicalRoute: "/command/investor-pitch",
    source: "showcase",
    mutability: "read-only",
    notes: "Presentation layer; planning outputs and claims require source-register evidence.",
  },
  "/command/investor-pitch-external": {
    canonicalRoute: "/command/investor-pitch-external",
    source: "showcase",
    mutability: "read-only",
    notes:
      "External Bolt-hosted business review surfaced through the controlled Showcase navigation.",
  },
  "/command/stakeholder-portal": {
    canonicalRoute: "/command/stakeholder-portal",
    source: "showcase",
    mutability: "read-only",
    notes: "External read-only narrative separating verified, modeled and pending states.",
  },
  "/command/platform-walkthrough": {
    canonicalRoute: "/command/platform-walkthrough",
    source: "showcase",
    mutability: "read-only",
    notes: "Guided read-only demonstration linking back to command source evidence.",
  },
};
export const getRouteOwnership = (route: string) => routeOwnership[route];
export const ROUTE_FILE_EXCLUSIONS = new Set(["/command/inventory-ledgers/$ledger"]);
export const PUBLIC_REFERENCE_ROUTES = [
  "/",
  "/range",
  "/range/$tier",
  "/fit-calculator",
  "/inventory",
] as const;
export function validateRouteOwnership(): string[] {
  const errors: string[] = [];
  for (const [route, ownership] of Object.entries(routeOwnership)) {
    if (route !== "/command/inventory-ledgers/:ledger" && !routeRegistry[route])
      errors.push(`${route} is missing from routeRegistry`);
    if (ownership.canonicalRoute !== route && !routeRegistry[ownership.canonicalRoute])
      errors.push(`${route} points to an unregistered canonical route`);
    if (!ownership.notes.trim()) errors.push(`${route} has no ownership notes`);
  }
  return errors;
}
