#!/usr/bin/env node
/**
 * Run a command with `.grok/app-env.json` merged into its environment.
 *
 * `dev`, `build` and `preview` all route through this wrapper, so the dev
 * server, the built bundle and the preview server can never disagree about
 * `VITE_AUTH_ENABLED` — a divergence that only shows up as a built-output
 * mismatch long after the fact. Anything that starts Vite directly bypasses it.
 *
 * The wrapper also prepares the pinned HiGHS WebAssembly runtime as a relative
 * source asset. The `highs` package exports its Wasm file, but package-exported
 * Wasm currently crosses the TanStack/Rolldown split boundary inconsistently.
 * Copying the exact pinned file into `src/generated` lets Cloudflare's Vite
 * plugin own normal relative `.wasm` module handling without changing solver
 * version or fetching runtime code dynamically.
 *
 * The pinned HiGHS ESM loader is generated by Emscripten for web, worker and
 * Node runtimes. That generated loader uses `createRequire(import.meta.url)`.
 * Cloudflare's Worker bundle can expose the Node compatibility shim while
 * stripping the module URL, which makes `createRequire(undefined)` fail before
 * HiGHS can consume the already-bundled Wasm module. Before Vite runs we make
 * the generated loader resilient to that one host-specific condition. Node and
 * normal ESM runtimes still use their real module URL; only a missing URL gets
 * a synthetic file URL, and the solver continues to receive the pinned Wasm
 * module from VYNDI's bundle rather than reading or fetching it at runtime.
 *
 * Only `VITE_`-prefixed keys are honored from `.grok/app-env.json`: the file is
 * a build flag carrier, not a secret store, and only `VITE_` vars reach the
 * browser anyway. A real `process.env` entry always wins, so an explicit
 * override still works.
 *
 * On Cloudflare Workers Builds, `WORKERS_CI_COMMIT_SHA` is injected by the
 * platform for the exact Git commit being built. During that ephemeral build
 * checkout we copy it into `wrangler.jsonc` as the runtime text binding
 * `VYNDI_SOURCE_SHA`. This makes governed IBPE lineage deterministic without
 * requiring a manually maintained dashboard value or hardcoding a commit SHA.
 *
 * That precedence also means the file governs this workspace only. A deployed
 * build runs with the provider's project env, where the deployer sets
 * `VITE_AUTH_ENABLED` itself (today unconditionally `"true"`), so the deployed
 * flag is the platform's, not this file's.
 *
 * Vite picks the values up because `loadEnv` prefix-matches entries already in
 * `process.env`, which is why the merge has to happen before Vite starts.
 */
import { spawn } from "node:child_process";
import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { constants as osConstants } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const APP_ENV_REL_PATH = ".grok/app-env.json";

const VITE_PREFIX = "VITE_";
const WORKERS_SHA_KEY = "WORKERS_CI_COMMIT_SHA";
const RUNTIME_SHA_KEY = "VYNDI_SOURCE_SHA";
const HIGHS_ESM_REL_PATH = ["node_modules", "highs", "build", "highs.mjs"];
const HIGHS_SAFE_MODULE_URL =
  '(typeof import.meta.url === "string" ? import.meta.url : "file:///highs.mjs")';

/**
 * Parse an app-env document, keeping only `VITE_`-prefixed string entries.
 * Anything unparseable is an empty environment — a workspace without the file
 * must behave exactly like today (auth on, no overrides).
 */
export function parseAppEnv(text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    return {};
  }
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) return {};
  const env = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (!key.startsWith(VITE_PREFIX)) continue;
    if (typeof value !== "string") continue;
    env[key] = value;
  }
  return env;
}

/** The app env recorded under `root`, or `{}` when the file is absent. */
export function readAppEnv(root) {
  try {
    return parseAppEnv(readFileSync(join(root, APP_ENV_REL_PATH), "utf8"));
  } catch {
    return {};
  }
}

/** File values under the process environment: an explicit override wins. */
export function mergeAppEnv(appEnv, processEnv) {
  return { ...appEnv, ...processEnv };
}

/** Return the exact Workers Builds commit SHA when it is a plausible git SHA. */
export function workersCiCommitSha(processEnv) {
  const value = typeof processEnv?.[WORKERS_SHA_KEY] === "string"
    ? processEnv[WORKERS_SHA_KEY].trim()
    : "";
  return /^[0-9a-f]{7,64}$/i.test(value) ? value : undefined;
}

/**
 * Inject the Workers Builds commit SHA into the ephemeral Wrangler config.
 *
 * The repository file is never hardcoded with a SHA. Workers Builds checks out
 * the repository, this wrapper mutates only that temporary checkout, and the
 * following `wrangler deploy` publishes the same commit SHA as a runtime text
 * binding. Existing Wrangler vars are preserved.
 */
export function injectWorkersSourceSha(root, processEnv) {
  const sha = workersCiCommitSha(processEnv);
  if (!sha) return false;

  const configPath = join(root, "wrangler.jsonc");
  let config;
  try {
    config = JSON.parse(readFileSync(configPath, "utf8"));
  } catch {
    return false;
  }
  if (!config || typeof config !== "object" || Array.isArray(config)) return false;

  const existingVars = config.vars && typeof config.vars === "object" && !Array.isArray(config.vars)
    ? config.vars
    : {};
  config.vars = { ...existingVars, [RUNTIME_SHA_KEY]: sha };
  writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  return true;
}

export function preparePinnedHighsWasm(root) {
  const source = join(root, "node_modules", "highs", "build", "highs.wasm");
  const targetDir = join(root, "src", "generated");
  const target = join(targetDir, "highs.wasm");
  let sourceStat;
  try {
    sourceStat = statSync(source);
  } catch {
    return false;
  }
  if (!sourceStat.isFile()) return false;
  mkdirSync(targetDir, { recursive: true });
  copyFileSync(source, target);
  return true;
}

/**
 * Make the pinned Emscripten ESM loader safe when Cloudflare erases
 * `import.meta.url` while retaining the Node compatibility `createRequire`
 * shim. The replacement is intentionally narrow and build-time only.
 *
 * `highs@1.15.3` is pinned in package.json. If its generated loader no longer
 * contains `import.meta.url`, return false so the build fails visibly instead
 * of silently assuming an unknown dependency layout is safe.
 */
export function patchPinnedHighsEsmLoaderForCloudflare(root) {
  const loaderPath = join(root, ...HIGHS_ESM_REL_PATH);
  let source;
  try {
    source = readFileSync(loaderPath, "utf8");
  } catch {
    return false;
  }

  // Idempotent across dev/build/typecheck invocations in the same checkout.
  if (source.includes(HIGHS_SAFE_MODULE_URL)) return true;
  if (!source.includes("import.meta.url")) return false;

  const patched = source.replaceAll("import.meta.url", HIGHS_SAFE_MODULE_URL);
  writeFileSync(loaderPath, patched, "utf8");
  return true;
}

/**
 * Translate a child's `exit` `(code, signal)` into this process's exit status.
 *
 * Do not re-raise the signal with `process.kill(process.pid, signal)`: under
 * qemu-user (amd64 image builds on an arm host) a self-directed signal is
 * routinely delivered as SIGSEGV to the wrong process, which takes down the
 * test worker and fails the image build. `128 + signo` is what a shell reports
 * for a signal-killed command, so a cancelled `vite build` is still a failure.
 */
export function exitStatusFromChild(code, signal) {
  if (signal) {
    const signo = osConstants.signals[signal];
    return 128 + (typeof signo === "number" ? signo : 1);
  }
  return code ?? 1;
}

/** The workspace root (this file lives in `<root>/scripts/`). */
export function projectRoot() {
  return dirname(dirname(fileURLToPath(import.meta.url)));
}

/**
 * Whether `moduleUrl` is the script node was asked to run.
 *
 * Both sides are resolved through symlinks: node realpaths `import.meta.url`
 * but leaves `process.argv[1]` as typed, so comparing them raw makes a CLI
 * launched through a symlinked path (`/tmp` on macOS) a silent no-op.
 */
export function isMainModule(moduleUrl) {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return realpathSync(entry) === fileURLToPath(moduleUrl);
  } catch {
    return false;
  }
}

function main(argv) {
  const [command, ...args] = argv;
  if (!command) {
    console.error("usage: node scripts/with-app-env.mjs <command> [args…]");
    process.exit(2);
  }
  const root = projectRoot();
  const env = mergeAppEnv(readAppEnv(root), process.env);
  const workersSha = workersCiCommitSha(env);
  if (workersSha) {
    env[RUNTIME_SHA_KEY] = workersSha;
    if (!injectWorkersSourceSha(root, env)) {
      console.error("[with-app-env] Workers commit SHA is present but could not be injected into wrangler.jsonc.");
      process.exit(2);
    }
  }
  if (command === "vite") {
    if (!preparePinnedHighsWasm(root)) {
      console.error("[with-app-env] pinned HiGHS Wasm runtime is missing; run npm ci first.");
      process.exit(2);
    }
    if (!patchPinnedHighsEsmLoaderForCloudflare(root)) {
      console.error("[with-app-env] pinned HiGHS ESM loader could not be made Cloudflare-safe.");
      process.exit(2);
    }
  }
  const executable = process.platform === "win32" ? "npm.cmd" : command;
  const executableArgs =
    process.platform === "win32"
      ? ["exec", "--", command, ...args]
      : args;
  const child = spawn(executable, executableArgs, {
    stdio: "inherit",
    env,
    shell: process.platform === "win32",
  });
  // The dev server is long-running and is stopped by signalling this wrapper.
  for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
    process.on(signal, () => child.kill(signal));
  }
  child.on("error", (err) => {
    console.error(`[with-app-env] failed to run ${command}:`, err?.message || err);
    process.exit(127);
  });
  child.on("exit", (code, signal) => {
    process.exit(exitStatusFromChild(code, signal));
  });
}

if (isMainModule(import.meta.url)) {
  main(process.argv.slice(2));
}
